-- TODO
-- -- removes blizzard time clock
-- local function RemoveBlizTime(self, name)
--   if name == "Blizzard_TimeManager" then
--     TimeManagerClockButton:Hide()
--     TimeManagerClockButton:SetScript("OnShow", function(self)
--       TimeManagerClockButton:Hide()
--     end)
--   end
-- end
-- V.AddEventListener(RemoveBlizTime, "ADDON_LOADED")

-- TODO
-- -- time frame
-- local clock = V.CreateFrame("EUIClock", EUIMinimap, 45, 17)
-- clock:SetPoint("TOP", EUIMinimap, "TOP", 0, -4)
-- clock:SetFrameStrata("MEDIUM")
-- clock.text = clock:CreateString()
-- local displayFormat = string.join("", "%02d", ":%02d")
-- clock.text:SetPoint("CENTER")

-- --format
